// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utjjecykekujgxideane.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0amplY3lrZWt1amd4aWRlYW5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzE2NjMsImV4cCI6MjA2NDcwNzY2M30.btprxKnYQzDd0rH_HZYIQf2QztxO4vqQHITUE6xb1Rw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);